@url = http://localhost:3055

### ADD A NOTE
POST {{url}}/api/add-note
content-type: application/json
	
{
	"app_pin": "nnn",
	"body": "this is the first note",
	"rank": 1.1
}

### GET ALL NOTES
POST {{url}}/api/get-notes